from __future__ import annotations

from typing import Protocol

from swingtrading.models import BracketHandle, LedgerFill, Quote, Side, TradePlan


class Broker(Protocol):
    """Retail TWS execution port (Lynx / IBKR)."""

    def connect(self) -> None: ...

    def reconnect(self) -> None: ...

    def is_connected(self) -> bool: ...

    def quote(self, symbol: str) -> Quote: ...

    def position_qty(self, symbol: str) -> int: ...

    def buying_power(self) -> float: ...

    def order_margin(self, plan: TradePlan) -> float: ...

    def place_bracket(self, plan: TradePlan) -> BracketHandle: ...

    def cancel_bracket(self, handle: BracketHandle) -> None: ...

    def refresh_bracket(self, handle: BracketHandle) -> BracketHandle: ...

    def existing_bracket(self, plan: TradePlan) -> BracketHandle | None: ...

    def wait(self, seconds: float) -> None: ...

    def cancel_tagged_exits(self, fill: LedgerFill) -> None: ...

    def place_moc(self, symbol: str, side: Side, qty: int, order_ref: str) -> None: ...

    def tagged_exit_filled(self, fill: LedgerFill) -> str | None: ...

    def has_working_exit(self, fill: LedgerFill) -> bool: ...
